### PR TITLE
fix: Bolus progress view

### PR DESCRIPTION
**Pull request by bastiaanv**
I got a bug report from multiple people using the Dana pump where the bolus progress view showed the wrong values.
Example video of the issue: https://drive.google.com/file/d/1ibcAKbN7TiByifxZj2Y2gp9ZcVxLfiMT/view?pli=1

This isn't an issue on the original iAPS repo, so I used that repo as an inspiration to fix the issue:
https://github.com/Artificial-Pancreas/iAPS/blob/main/FreeAPS/Sources/Modules/Home/View/HomeRootView.swift#L727

IMG_2549

The progress view used the previous bolusAmount with the current bolusProgress. Unsure why/how DanaKit is reporting the bolus amount later than other drivers, but this is the same solution Jon is using currently

Thank you Matthias Momm & Alen Djonko for bringing this to my attention

### CODE REVIEW

**Comment by mountrcg** [comment]
@bastiaanv sry totally did not see this also was away for a while. I am not used to this great participation - thank you. Will look at it now.

**Review by mountrcg — APPROVED** [review]
'APPROVE' performed by Xcode.

**Comment by bastiaanv** [comment]
No problem. Saw that the link to iaps is oudated

**Comment by bastiaanv** [comment]
Closing since it is part of default branch!

**Pull request closed without merging**
